version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - tlmhl-db:/var/lib/postgresql/data
    networks:
      - api

  redis:
    image: "redis:alpine"
    networks:
      - api

  api:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/tlmhl
    environment:
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: 1
    extra_hosts:
      - "dns:8.8.8.8"
    networks:
      - api

volumes:
  tlmhl-db: {}
  app: {}

networks:
  api: