version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - tlmhl-db:/var/lib/postgresql/data

volumes:
  tlmhl-db: {}
